ejercicio numero 2

In [1]:
import pandas as pd

p = lambda x: 10*x**4 - 31*x**3 + 18*x**2 + 2*x - 1
dp = lambda x: 40*x**3 - 93*x**2 + 36*x + 2

def Newton(p, dp, x0, tol, maxiter):
    x = x0
    for iters in range(maxiter):
        fx = p(x)
        dfx = dp(x)
        if dfx == 0: break
        x_new = x - fx / dfx
        error = abs(x_new - x)
        if error < tol:
            return x_new, iters + 1, error
        x = x_new
    return x, maxiter, error

def Newtontabla(p, dp, x0, tol, maxiter):
    x = x0
    hx, he = [], []
    for i in range(maxiter):
        fx = p(x)
        dfx = dp(x)
        if dfx == 0: break
        x_new = x - fx / dfx
        error = abs(x_new - x)
        hx.append(x_new)
        he.append(error)
        if error < tol:
            break
        x = x_new
    return pd.DataFrame({'Iteraciones': hx, 'Error': he})

In [2]:
x0 = -0.3
tol = 1e-7
maxiter = 30

r1, iters, error = Newton(p, dp, x0, tol, maxiter)

print("La solución obtenida para r1 es x = %s" % r1)
print("El numero de iteraciones fue de %s" % iters)
print("El error obtenido fue %s" % error)

La solución obtenida para r1 es x = -0.23851648071345039
El numero de iteraciones fue de 5
El error obtenido fue 5.720979245893432e-13

In [3]:
Newtontabla(p, dp, x0, tol, maxiter)

   Iteraciones         Error
0    -0.248603  5.139726e-02
1    -0.238856  9.746822e-03
2    -0.238517  3.390337e-04
3    -0.238516  4.037135e-07
4    -0.238516  5.720979e-13

In [4]:
x0 = 0.2
tol = 1e-7
maxiter = 30

r2, iters, error = Newton(p, dp, x0, tol, maxiter)

print("La solución obtenida para r2 es x = %s" % r2)
print("El numero de iteraciones fue de %s" % iters)
print("El error obtenido fue %s" % error)

La solución obtenida para r2 es x = 0.21922359359558485
El numero de iteraciones fue de 3
El error obtenido fue 6.334343882752336e-10

In [5]:
Newtontabla(p, dp, x0, tol, maxiter)

   Iteraciones         Error
0     0.219310  1.931034e-02
1     0.219224  8.675060e-05
2     0.219224  6.334344e-10

In [8]:
x0 = 0.8
tol = 1e-7
maxiter = 30

r3, iters, error = Newton(p, dp, x0, tol, maxiter)

print("La solución obtenida para r3 es x = %s" % r3)
print("El numero de iteraciones fue de %s" % iters)
print("El error obtenido fue %s" % error)

La solución obtenida para r3 es x = 0.8385164807134505
El numero de iteraciones fue de 4
El error obtenido fue 6.724389933765451e-10

In [9]:
Newtontabla(p, dp, x0, tol, maxiter)

   Iteraciones         Error
0     0.841748  4.174757e-02
1     0.838536  3.212026e-03
2     0.838516  1.906592e-05
3     0.838516  6.724390e-10

In [6]:
x0 = 2.3
tol = 1e-7
maxiter = 30

r4, iters, error = Newton(p, dp, x0, tol, maxiter)

print("La solución obtenida para r4 es x = %s" % r4)
print("El numero de iteraciones fue de %s" % iters)
print("El error obtenido fue %s" % error)

La solución obtenida para r4 es x = 2.280776406404414
El numero de iteraciones fue de 4
El error obtenido fue 3.8324898810060404e-13

In [7]:
Newtontabla(p, dp, x0, tol, maxiter)

   Iteraciones         Error
0     2.281336  1.866432e-02
1     2.280777  5.587825e-04
2     2.280776  4.921686e-07
3     2.280776  3.832490e-13