literal b) del primer ejercicio

In [3]:
import math
import pandas as pd


f = lambda x: x**2 - 100*x*math.sin(x) + (10*math.sin(x))**2
df = lambda x: 2*x - 100*(math.sin(x) + x*math.cos(x)) + 200*math.sin(x)*math.cos(x)

def Biseccion(func, a, b, tol, maxiter=50):
    iter = 0
    error = tol + 1
    lista_x = []
    lista_e = []

    while error > tol and iter < maxiter:
        x = (a + b) / 2
        error = abs(b - a) / 2
        iter += 1

        if func(a) * func(x) < 0:
            b = x
        else:
            a = x

        lista_x.append(x)
        lista_e.append(error)

    tabla = pd.DataFrame({'Iteraciones': lista_x, 'Error': lista_e})
    return x, iter, error, tabla

In [2]:
a, b = 2.1, 3.2
tol = 1e-3
maxiter = 30

x, iters, error, tabla_f = Biseccion(f, a, b, tol, maxiter)

print("La solución obtenida fue %s" % x)
print("Las iteraciones realizadas fueron %s" % iters)
print("El error obtenido fue %s" % error)
display(tabla_f)

La solución obtenida fue 3.110302734375
Las iteraciones realizadas fueron 11
El error obtenido fue 0.0005371093749999556

    Iteraciones     Error
0      2.650000  0.550000
1      2.925000  0.275000
2      3.062500  0.137500
3      3.131250  0.068750
4      3.096875  0.034375
5      3.114063  0.017188
6      3.105469  0.008594
7      3.109766  0.004297
8      3.111914  0.002148
9      3.110840  0.001074
10     3.110303  0.000537

In [4]:
a, b = -3, -2
tol = 1e-3
maxiter = 30

x, iters, error, tabla_df = Biseccion(df, a, b, tol, maxiter)

print("La solución obtenida fue %s" % x)
print("Las iteraciones realizadas fueron %s" % iters)
print("El error obtenido fue %s" % error)
display(tabla_df)

La solución obtenida fue -2.3544921875
Las iteraciones realizadas fueron 10
El error obtenido fue 0.0009765625

   Iteraciones     Error
0    -2.500000  0.500000
1    -2.250000  0.250000
2    -2.375000  0.125000
3    -2.312500  0.062500
4    -2.343750  0.031250
5    -2.359375  0.015625
6    -2.351562  0.007812
7    -2.355469  0.003906
8    -2.353516  0.001953
9    -2.354492  0.000977